version: "3"

services: 
  web:
    build: "./web"
    ports: 
      - "5000:5000"
    links:
      - my_db
  my_db:
    build: "./db"
    # image: mongo:3.6.4
    environment: 
      - MONGO_INITDB_DATABASE=ProductManagementDB
    ports:
      - 27017:27017
    

  